apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordernpay
  labels:
    app: ordernpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordernpay
  template:
    metadata:
      labels:
        app: ordernpay
    spec:
      containers:
        - name: ordernpay
          image: username/ordernpay:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
